version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.8.4
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-3.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka-producer:
    build: .
    command: ["python", "producer.py"]
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  spark-consumer:
    build: .
    command: ["spark-submit", "KafkaSparkConsumer.py"]
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
